repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort -rc .
        language: system
        require_serial: true
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types: [python]

#      - id: pydocstyle
#        name: pydocstyle
#        entry: pydocstyle
#        language: system
#        types: [python]

      - id: pylint
        name: pylint
        entry: pylint mogp_decomposition tests
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        require_serial: true
        types: [python]

#      - id: poetry
#        name: poetry
#        entry: poetry check
#        language: system
#        pass_filenames: false
#        files: pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
